- id: '1672909779332'
  alias: HA restart
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: shell_command.ha_start
    data: {}
  mode: single
