- id: '1672909779332'
  alias: HA restart
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: shell_command.ha_start
    data: {}
  mode: single
- id: '1691497590953'
  alias: Nordpool - Reload Integration
  description: Nødvendig for å få inn timeverdier, dessverre...
  use_blueprint:
    path: erlendsellie/nordpool_reload.yaml
    input:
      entity: sensor.nordpool_kwh_no2_nok_3_095_025
