
# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  allowlist_external_dirs:    
    - "/media"
    - "/tmp"

http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24  # Local Lan
    - 172.10.0.0/24  # Docker network

shell_command:
  ha_start: curl http://192.168.1.226:1880/endpoint/ha_start

logger:
  default: warn
  # logs:
  #   components.august: debug
    
duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

homekit:

nordpool:

# Example configuration.yaml entry
climate:
  - platform: generic_thermostat
    unique_id: climate.soverom_1_varmeovn
    name: Soverom 1 Varmeovn
    heater: switch.smartplugg1
    target_sensor: sensor.temperatur_soverom_1   

sensor: !include sensor.yaml

template: !include template.yaml

mqtt:
  sensor:
    - name: "E-Golf SOC"
      unique_id: sensor.e_golf_soc
      state_topic: "E_Golf/SOC"
      unit_of_measurement: "%"
      value_template: "{{ value_json.soc | float(0) }}"
    - name: "E-Golf Kilometerstand"
      unique_id: sensor.e_golf_kmstand
      state_topic: "E_Golf/Odometer"
      unit_of_measurement: "km"
      value_template: "{{ value_json.odometer }}"
 
#webhook:

#  zigbee2mqtt_networkmap:
#    #topic: your topic (optional, default zigbee2mqtt)
#  panel_iframe:
#    networkmap:
#      title: 'Zigbee Map'
#      url: '/local/community/zigbee2mqtt_networkmap/map.html'
#      icon: 'mdi:graphql'

tts:
  - platform: microsoft
    api_key: !secret microsoft_tts
    language: nb-no
    gender: Male
    type: FinnNeural
    region: westeurope
    # rate: 20
    # volume: -50
    # pitch: high
    # contour: (0, 0) (100, 100)
    
  # - platform: google_cloud
  #   key_file: googlecloud.json
  #   voice: nb-NO-Wavenet-B
  #   text_type: ssml
  #   profiles:
  #     - medium-bluetooth-speaker-class-device

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes
