# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  allowlist_external_dirs:
    - "/media"
    - "/tmp"

http:
  ip_ban_enabled: false
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24 # Local Lan
    - 172.10.0.0/24 # Docker network

#shell_command:
#  ha_start: curl http://192.168.1.226:1880/endpoint/ha_start

logger:
  default: warn
  # logs:
  #   components.august: debug

homekit:

nordpool:

sensor: !include sensor.yaml

template: !include template.yaml

mqtt:
  sensor:
    - name: "E-Golf SOC"
      unique_id: sensor.e_golf_soc
      state_topic: "E_Golf/SOC"
      unit_of_measurement: "%"
      value_template: "{{ value_json.soc | float(0) }}"
    - name: "E-Golf Kilometerstand"
      unique_id: sensor.e_golf_kmstand
      state_topic: "E_Golf/Odometer"
      unit_of_measurement: "km"
      value_template: "{{ value_json.odometer }}"

# Database
recorder:
  db_url: !secret psql_connector_string
  db_retry_wait: 10 # Wait 10 seconds before retrying
  purge_keep_days: 3650
  exclude:
    domains:
      - automation
      - updater
    entity_globs:
      - sensor.weather_*
    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date
    event_types:
      - call_service # Don't record service calls

tts:
  - platform: microsoft
    api_key: !secret microsoft_tts
    language: nb-no
    gender: Male
    type: FinnNeural
    region: westeurope
    # rate: 20
    # volume: -50
    # pitch: high
    # contour: (0, 0) (100, 100)

  # - platform: google_cloud
  #   key_file: googlecloud.json
  #   voice: nb-NO-Wavenet-B
  #   text_type: ssml
  #   profiles:
  #     - medium-bluetooth-speaker-class-device

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes
