blueprint:
  name: Nordpool - Reload Integration
  description: Reload Nordpool Integration When the API fails to fetch new data, or
    the sensor becomes unavailable or unknown.
  domain: automation
  input:
    entity:
      name: Nordpool Sensor
      description: Your Nordpool Sensor
      selector:
        entity:
          integration: nordpool
          domain:
          - sensor
          multiple: false
    notify:
      name: Notify
      description: Notify with a Persistent Notification in Home Assistant whenever
        the Nordpool integration is reloaded.
      default: true
      selector:
        boolean: {}
  source_url: https://github.com/erlendsellie/HomeAssistantConfig/blob/master/blueprints/automation/erlendsellie/nordpool_reload.yaml
mode: single
max_exceeded: silent
trigger_variables:
  entity: !input entity
trigger:
- platform: template
  value_template: "{%set nordpool = states[entity]%} {%if nordpool.attributes.tomorrow
    is defined %}\n  {%set tomorrow = nordpool.attributes.tomorrow %}\n  {%set tomorrowvalue
    = tomorrow[1] or 0 | float(default=0) %}\n{%else%}\n  {%set tomorrowvalue = 0
    %}\n{%endif%}       {%set shouldBeValid = (now().hour > 13) and (now().minute
    > 0)%} {{shouldBeValid and tomorrowvalue < 0.01}}"
  for:
    minutes: 1
- platform: template
  value_template: "{%set nordpool = states[entity]%} {%if nordpool.attributes.tomorrow
    is defined %}\n  {%set tomorrow = nordpool.attributes.tomorrow %}\n  {%set tomorrowvalue
    = tomorrow[1] or 0 | float(default=0) %}\n{%else%}\n  {%set tomorrowvalue = 0
    %}\n{%endif%}       {%set shouldBeValid = (now().hour > 12) and (now().minute
    > 45)%} {{shouldBeValid and tomorrowvalue < 0.01}}"
  for:
    minutes: 1
- platform: template
  value_template: "{%set nordpool = states[entity]%} {%if nordpool.attributes.tomorrow
    is defined %}\n  {%set tomorrow = nordpool.attributes.tomorrow %}\n  {%set tomorrowvalue
    = tomorrow[1] or 0 | float(default=0) %}\n{%else%}\n  {%set tomorrowvalue = 0
    %}\n{%endif%}       {%set shouldBeValid = (now().hour > 12) and (now().minute
    > 30)%} {{shouldBeValid and tomorrowvalue < 0.01}}"
  for:
    minutes: 1
- platform: template
  value_template: "{%set nordpool = states[entity]%} {%if nordpool.attributes.tomorrow
    is defined %}\n  {%set tomorrow = nordpool.attributes.tomorrow %}\n  {%set tomorrowvalue
    = tomorrow[1] or 0 | float(default=0) %}\n{%else%}\n  {%set tomorrowvalue = 0
    %}\n{%endif%}       {%set shouldBeValid = (now().hour > 12) and (now().minute
    > 15)%} {{shouldBeValid and tomorrowvalue < 0.01}}"
  for:
    minutes: 1
- platform: template
  value_template: "{%set nordpool = states[entity]%} {{\n  nordpool == 'unknown' or\n
    \ nordpool == 'unavailable'\n}}"
  for:
    minutes: 1
action:
- variables:
    entity: !input entity
    notify: !input notify
- service: homeassistant.reload_config_entry
  entity_id: !input entity
- condition: '{{ notify == true }}'
- delay:
    seconds: 10
- service: persistent_notification.create
  data:
    title: Nordpool var utilgjengelig, relastet integrasjonen
    message: State nå er {{states(entity)}}
